import {
  CardDesign,
  PhysicalCard,
  UserProfile,
  Customer,
  Order,
  NfcCard,
} from '@/types/taplink';

export const INITIAL_DEMO_PROFILE: UserProfile = {
  slug: 'haziq',
  fullName: 'Haziq Aiman',
  jobTitle: 'Creative Director',
  company: 'TapLinkPro',
  bio: 'Crafting luxury physical NFC identities, bespoke tactile stationery and seamless contactless communication.',
  location: 'Kuala Lumpur, Malaysia',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
  avatarCrop: {
    x: 0,
    y: 0,
    zoom: 1,
    rotate: 0,
  },
  contacts: {
    phone: '+60 16-52353789',
    whatsapp: '601652353789',
    telegram: '@taplinkpro',
    email: 'dhaziq.aiman@gmail.com',
    website: 'https://taplinkpro.id',
    linkedin: 'haziqaiman',
    instagram: 'taplinkpro',
  },
  appearance: {
    theme: 'obsidian',
    cardStyle: 'executive',
  },
  payment: {
    enabled: false,
    duitNow: '+601652353789',
    bankName: 'Maybank Islamic Berhad',
    bankAccount: '5140 8820 9132',
    paypal: 'paypal.me/haziqaiman',
  },
  isDemo: true,
  updatedAt: '2026-03-18T10:00:00Z',
};

export const LUXURY_CARD_DESIGNS: CardDesign[] = [
  {
    id: 'design-pvc-signature',
    name: 'TapLink Signature Matte PVC',
    category: 'Matte PVC NFC',
    finish: 'Velvet Soft-Touch Matte Black with Gold Hotstamp',
    material: 'High-Density PVC with Internal NXP NTAG213/424 Micro-Antenna',
    description: 'Our flagship default custom design: premium velvet-touch matte black finish, crisp gold hotstamped logo, durable water-resistant body, and instantaneous tap response.',
    cardColor: '#1a1918',
    accentColor: '#C9A24B',
    weight: '5.5g featherlight durable card',
    price: '$29 USD',
    availability: 'IN_STOCK',
    tag: 'Default Starting Model',
  },
  {
    id: 'design-pvc-custom',
    name: 'Bespoke Custom Matte PVC',
    category: 'Matte PVC NFC',
    finish: 'Custom Design Print Matte PVC',
    material: 'Edge-to-Edge Custom UV Matte Print PVC with Embedded NFC',
    description: 'Full custom design tailored with your company typography, brand palette, and custom QR code reverse engraving.',
    cardColor: '#242321',
    accentColor: '#DFB864',
    weight: '5.5g featherlight durable card',
    price: '$39 USD',
    availability: 'IN_STOCK',
    tag: 'Custom Branding',
  },
  {
    id: 'design-obsidian',
    name: 'The Obsidian Sovereign (Metal)',
    category: 'Solid Metal (Coming Soon)',
    finish: 'Matte Obsidian Black Metal',
    material: 'Aerospace-Grade 6061 Anodized Aluminium',
    description: 'Deep micro-textured matte black surface with laser-vaporized gold micro-inlay and shielded internal high-frequency NFC antenna.',
    cardColor: '#161514',
    accentColor: '#C9A24B',
    weight: '24.5g solid metal weight',
    price: '$129 USD',
    availability: 'WAITLIST',
    tag: 'Coming Soon',
  },
  {
    id: 'design-titanium',
    name: 'Titanium Executive (Metal)',
    category: 'Solid Metal (Coming Soon)',
    finish: 'Brushed Titanium Steel',
    material: 'Grade-5 Aerospace Titanium Alloy',
    description: 'Unidirectional hand-brushed satin grain with chamfered polished edges and precision diamond-cut monogram recess.',
    cardColor: '#2b2a28',
    accentColor: '#e0ded9',
    weight: '26.8g aerospace alloy',
    price: '$169 USD',
    availability: 'WAITLIST',
    tag: 'Coming Soon',
  },
  {
    id: 'design-champagne',
    name: 'Aura Champagne Brass (Metal)',
    category: 'Precious Ingot (Coming Soon)',
    finish: 'Champagne Gold Brass',
    material: 'Forged Architectural Brass with PVD Gold Seal',
    description: 'Subtle warm champagne luster treated with anti-tarnish microscopic ceramic coat. Precision resonant coil engineered for through-metal NFC broadcast.',
    cardColor: '#362f22',
    accentColor: '#E6C676',
    weight: '28.2g dense ingot feel',
    price: '$149 USD',
    availability: 'WAITLIST',
    tag: 'Coming Soon',
  },
  {
    id: 'design-24k',
    name: 'Imperial 24K Mirror Ingot (Metal)',
    category: 'Precious Ingot (Coming Soon)',
    finish: '24K Gold Mirror Ingot',
    material: 'Heavy Brass Ingot with 5-Micron 24K Hard Gold Plating',
    description: 'Jewelry-grade mirror polished gold exterior with individual laser serial numbering and bespoke tactile engraving.',
    cardColor: '#241d0f',
    accentColor: '#FFD700',
    weight: '32.0g heaviest heirloom weight',
    price: '$249 USD',
    availability: 'WAITLIST',
    tag: 'Coming Soon',
  },
];

// Initial physical card bound to demo customer account
export const INITIAL_PHYSICAL_CARD: PhysicalCard = {
  id: 'card_demo_01',
  serialNumber: 'TLP-000001',
  activationHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  activationCode: 'A82K-X91P',
  status: 'ACTIVE',
  designId: 'design-obsidian',
  designName: 'The Obsidian Sovereign',
  finish: 'Matte Obsidian Black',
  batchNumber: 'BATCH-2026-Q1',
  nfcChipType: 'NXP NTAG424 DNA (AES-128)',
  activatedAt: '2026-03-12T10:14:00Z',
  linkedSlug: 'haziq',
  tapCount: 142,
  isHardwareLocked: false,
};

// Available unclaimed hardware cards for customer activation testing
export const UNCLAIMED_TEST_CARDS: PhysicalCard[] = [
  {
    id: 'card_unclaimed_01',
    serialNumber: 'TLP-000004',
    activationHash: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    activationCode: 'D94K-W12T',
    status: 'AVAILABLE',
    designId: 'design-crystal',
    designName: 'Frosted Ghost Hybrid',
    finish: 'Frosted Crystal Hybrid',
    batchNumber: 'BATCH-2026-Q1',
    nfcChipType: 'NXP NTAG424 DNA',
    activatedAt: null,
    linkedSlug: null,
    tapCount: 0,
    isHardwareLocked: false,
  },
  {
    id: 'card_unclaimed_02',
    serialNumber: 'TLP-000005',
    activationHash: 'a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e',
    activationCode: 'E62M-Q88V',
    status: 'AVAILABLE',
    designId: 'design-24k',
    designName: 'Imperial 24K Mirror Ingot',
    finish: '24K Gold Mirror Ingot',
    batchNumber: 'BATCH-2026-Q1',
    nfcChipType: 'NXP NTAG424 DNA',
    activatedAt: null,
    linkedSlug: null,
    tapCount: 0,
    isHardwareLocked: false,
  },
];

// Customer directory for small business operations
export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    name: 'Haziq Aiman',
    email: 'dhaziq.aiman@gmail.com',
    phone: '+60 16-52353789',
    accountType: 'PAID_CUSTOMER',
    cardStatus: 'ACTIVE',
    orderStatus: 'DELIVERED',
    createdDate: '2026-02-10',
    slug: 'haziq',
    jobTitle: 'Creative Director',
    company: 'TapLinkPro',
    activeCardSerial: 'TLP-000001',
  },
  {
    id: 'cust_02',
    name: 'Sophia Chen',
    email: 'sophia.chen@apexcapital.sg',
    phone: '+65 9123 4567',
    accountType: 'PAID_CUSTOMER',
    cardStatus: 'ACTIVE',
    orderStatus: 'DELIVERED',
    createdDate: '2026-02-18',
    slug: 'sophia-chen',
    jobTitle: 'Managing Partner',
    company: 'Apex Capital Singapore',
    activeCardSerial: 'TLP-000002',
  },
  {
    id: 'cust_03',
    name: 'Marcus Vance',
    email: 'm.vance@vanceholdings.co.uk',
    phone: '+44 20 7946 0912',
    accountType: 'PAID_CUSTOMER',
    cardStatus: 'ACTIVE',
    orderStatus: 'SHIPPED',
    createdDate: '2026-03-01',
    slug: 'marcus-vance',
    jobTitle: 'Chief Executive Officer',
    company: 'Vance Holdings London',
    activeCardSerial: 'TLP-000003',
  },
  {
    id: 'cust_04',
    name: 'Elena Rostova',
    email: 'elena@rostova-design.ch',
    phone: '+41 22 731 8890',
    accountType: 'REGISTERED_USER',
    cardStatus: 'NO_CARD',
    orderStatus: 'PENDING_PAYMENT',
    createdDate: '2026-03-14',
    slug: 'elena-rostova',
    jobTitle: 'Principal Architect',
    company: 'Rostova Atelier Zurich',
  },
  {
    id: 'cust_05',
    name: 'Tariq Al-Mansoor',
    email: 'tariq@gulfexec.ae',
    phone: '+971 50 123 4567',
    accountType: 'REGISTERED_USER',
    cardStatus: 'NO_CARD',
    orderStatus: 'PRODUCTION',
    createdDate: '2026-03-15',
    slug: 'tariq',
    jobTitle: 'Executive Director',
    company: 'Gulf Executive Aviation',
  },
];

// Order management with realistic 6-stage lifecycle
export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-2026-101',
    customer: {
      name: 'Haziq Aiman',
      email: 'dhaziq.aiman@gmail.com',
      phone: '+60 16-52353789',
      shippingAddress: 'Tower 2, Level 38, KLCC Suites, 50088 Kuala Lumpur, Malaysia',
    },
    selectedDesign: {
      id: 'design-obsidian',
      name: 'The Obsidian Sovereign',
      finish: 'Matte Obsidian Black',
      price: '$129 USD',
    },
    engraving: {
      name: 'Haziq Aiman',
      subtext: 'Creative Director',
    },
    quantity: 1,
    price: '$129 USD',
    paymentStatus: 'CONFIRMED',
    productionStatus: 'DELIVERED',
    shippingStatus: 'DELIVERED',
    trackingNumber: 'MY-DHL-88912',
    associatedCardSerialNumber: 'TLP-000001',
    createdDate: '2026-02-08',
  },
  {
    id: 'ORD-2026-102',
    customer: {
      name: 'Sophia Chen',
      email: 'sophia.chen@apexcapital.sg',
      phone: '+65 9123 4567',
      shippingAddress: '10 Marina Boulevard, #32-01 Marina Bay Financial Centre, Singapore 018983',
    },
    selectedDesign: {
      id: 'design-champagne',
      name: 'Aura Champagne Brass',
      finish: 'Champagne Gold Brass',
      price: '$149 USD',
    },
    engraving: {
      name: 'Sophia Chen',
      subtext: 'Managing Partner',
    },
    quantity: 1,
    price: '$149 USD',
    paymentStatus: 'CONFIRMED',
    productionStatus: 'DELIVERED',
    shippingStatus: 'DELIVERED',
    trackingNumber: 'SG-FEDEX-9921',
    associatedCardSerialNumber: 'TLP-000002',
    createdDate: '2026-02-16',
  },
  {
    id: 'ORD-2026-103',
    customer: {
      name: 'Marcus Vance',
      email: 'm.vance@vanceholdings.co.uk',
      phone: '+44 20 7946 0912',
      shippingAddress: '25 Bank Street, Canary Wharf, London E14 5JP, United Kingdom',
    },
    selectedDesign: {
      id: 'design-24k',
      name: 'Imperial 24K Mirror Ingot',
      finish: '24K Gold Mirror Ingot',
      price: '$249 USD',
    },
    engraving: {
      name: 'Marcus Vance',
      subtext: 'Chief Executive Officer',
    },
    quantity: 1,
    price: '$249 USD',
    paymentStatus: 'CONFIRMED',
    productionStatus: 'READY_TO_SHIP',
    shippingStatus: 'SHIPPED',
    trackingNumber: 'UK-DHL-44192',
    associatedCardSerialNumber: 'TLP-000003',
    createdDate: '2026-03-01',
  },
  {
    id: 'ORD-2026-104',
    customer: {
      name: 'Tariq Al-Mansoor',
      email: 'tariq@gulfexec.ae',
      phone: '+971 50 123 4567',
      shippingAddress: 'DIFC Gate Village Building 04, Level 5, Dubai, UAE',
    },
    selectedDesign: {
      id: 'design-titanium',
      name: 'Titanium Executive',
      finish: 'Brushed Titanium Steel',
      price: '$169 USD',
    },
    engraving: {
      name: 'Tariq Al-Mansoor',
      subtext: 'Executive Director',
    },
    quantity: 1,
    price: '$169 USD',
    paymentStatus: 'CONFIRMED',
    productionStatus: 'PRODUCTION',
    shippingStatus: 'NOT_SHIPPED',
    trackingNumber: null,
    associatedCardSerialNumber: null,
    createdDate: '2026-03-12',
  },
  {
    id: 'ORD-2026-105',
    customer: {
      name: 'Elena Rostova',
      email: 'elena@rostova-design.ch',
      phone: '+41 22 731 8890',
      shippingAddress: 'Bahnhofstrasse 45, 8001 Zurich, Switzerland',
    },
    selectedDesign: {
      id: 'design-ceramic',
      name: 'Ceramic Apex White',
      finish: 'Ceramic Polar White',
      price: '$189 USD',
    },
    engraving: {
      name: 'Elena Rostova',
      subtext: 'Principal Architect',
    },
    quantity: 1,
    price: '$189 USD',
    paymentStatus: 'PENDING',
    productionStatus: 'REQUESTED',
    shippingStatus: 'NOT_SHIPPED',
    trackingNumber: null,
    associatedCardSerialNumber: null,
    createdDate: '2026-03-14',
  },
];

// Physical NFC Card Vault Inventory
export const INITIAL_NFC_CARDS: NfcCard[] = [
  {
    serialNumber: 'TLP-000001',
    design: 'The Obsidian Sovereign',
    finish: 'Matte Obsidian Black',
    status: 'ACTIVE',
    customer: 'Haziq Aiman',
    customerEmail: 'dhaziq.aiman@gmail.com',
    createdDate: '2026-01-15',
    activatedDate: '2026-02-12',
    activationCode: 'A82K-X91P',
  },
  {
    serialNumber: 'TLP-000002',
    design: 'Aura Champagne Brass',
    finish: 'Champagne Gold Brass',
    status: 'ACTIVE',
    customer: 'Sophia Chen',
    customerEmail: 'sophia.chen@apexcapital.sg',
    createdDate: '2026-01-20',
    activatedDate: '2026-02-20',
    activationCode: 'B39J-L24M',
  },
  {
    serialNumber: 'TLP-000003',
    design: 'Imperial 24K Mirror Ingot',
    finish: '24K Gold Mirror Ingot',
    status: 'ASSIGNED',
    customer: 'Marcus Vance',
    customerEmail: 'm.vance@vanceholdings.co.uk',
    createdDate: '2026-01-25',
    activatedDate: null,
    activationCode: 'C71P-R58N',
  },
  {
    serialNumber: 'TLP-000004',
    design: 'Frosted Ghost Hybrid',
    finish: 'Frosted Crystal Hybrid',
    status: 'AVAILABLE',
    customer: null,
    customerEmail: null,
    createdDate: '2026-02-01',
    activatedDate: null,
    activationCode: 'D94K-W12T',
  },
  {
    serialNumber: 'TLP-000005',
    design: 'Imperial 24K Mirror Ingot',
    finish: '24K Gold Mirror Ingot',
    status: 'AVAILABLE',
    customer: null,
    customerEmail: null,
    createdDate: '2026-02-10',
    activatedDate: null,
    activationCode: 'E62M-Q88V',
  },
  {
    serialNumber: 'TLP-000006',
    design: 'Ceramic Apex White',
    finish: 'Ceramic Polar White',
    status: 'AVAILABLE',
    customer: null,
    customerEmail: null,
    createdDate: '2026-02-15',
    activatedDate: null,
    activationCode: 'F15T-Z43B',
  },
];

/**
 * Calculates genuine profile completion percentage based on real filled fields.
 * Never hardcodes numbers.
 */
export function calculateProfileCompletion(profile: UserProfile): {
  percentage: number;
  completedCount: number;
  totalCount: number;
  missingFields: string[];
} {
  const checkList: { label: string; done: boolean }[] = [
    { label: 'Profile Photo', done: Boolean(profile.avatarUrl && profile.avatarUrl.trim().length > 0) },
    { label: 'Full Name', done: Boolean(profile.fullName && profile.fullName.trim().length > 0) },
    { label: 'Job Title', done: Boolean(profile.jobTitle && profile.jobTitle.trim().length > 0) },
    { label: 'Company / Organization', done: Boolean(profile.company && profile.company.trim().length > 0) },
    { label: 'Short Biography', done: Boolean(profile.bio && profile.bio.trim().length > 0) },
    { label: 'Location', done: Boolean(profile.location && profile.location.trim().length > 0) },
    { label: 'Direct Phone', done: Boolean(profile.contacts.phone && profile.contacts.phone.trim().length > 0) },
    { label: 'Primary Email', done: Boolean(profile.contacts.email && profile.contacts.email.trim().length > 0) },
    { label: 'WhatsApp', done: Boolean(profile.contacts.whatsapp && profile.contacts.whatsapp.trim().length > 0) },
    { label: 'Telegram Handle', done: Boolean(profile.contacts.telegram && profile.contacts.telegram.trim().length > 0) },
    { label: 'LinkedIn Profile', done: Boolean(profile.contacts.linkedin && profile.contacts.linkedin.trim().length > 0) },
    { label: 'Official Website', done: Boolean(profile.contacts.website && profile.contacts.website.trim().length > 0) },
  ];

  const completed = checkList.filter((item) => item.done);
  const missing = checkList.filter((item) => !item.done).map((item) => item.label);
  const percentage = Math.round((completed.length / checkList.length) * 100);

  return {
    percentage,
    completedCount: completed.length,
    totalCount: checkList.length,
    missingFields: missing,
  };
}
